# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d1f7f66630a65957a695427b85dff07c0f160b2ee47d7553a5cf70b5508bcaaf38b2f8dbf708a856e3df94ef801986be6635a616f563dde02f7c2e3252e287d

test:
  secret_key_base: cd7ecb88fdfd140caa0a11ce0c786e9e648ad37a67805b30e2733734543c94164520a3ce3fadb3e4148bb83b4750b3c616e823af33bd7ef8fb3e12864ed892fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
